# Generated by Django 5.0.6 on 2026-01-17 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=100, unique=True)),
                ('latitude', models.FloatField(help_text='Latitude coordinate')),
                ('longitude', models.FloatField(help_text='Longitude coordinate')),
                ('accuracy', models.FloatField(blank=True, help_text='Location accuracy in meters', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this location was recorded')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user is currently active')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time this user was seen')),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['device_id'], name='core_userlo_device__40c433_idx'), models.Index(fields=['last_seen'], name='core_userlo_last_se_1cd1e9_idx'), models.Index(fields=['is_active'], name='core_userlo_is_acti_35e182_idx')],
            },
        ),
    ]
