# Generated by Django 5.0.6 on 2026-01-18 06:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('arima', 'ARIMA'), ('sarima', 'SARIMA'), ('prophet', 'Prophet'), ('lstm', 'LSTM'), ('xgboost', 'XGBoost'), ('linear', 'Régression Linéaire'), ('random_forest', 'Random Forest')], max_length=50)),
                ('target_column', models.CharField(max_length=100)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('forecast_steps', models.IntegerField()),
                ('forecast_type', models.CharField(blank=True, max_length=50, null=True)),
                ('forecast_interval', models.CharField(blank=True, max_length=50, null=True)),
                ('predictions', models.JSONField()),
                ('actual_values', models.JSONField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de prévision',
                'verbose_name_plural': 'Historiques de prévisions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('wilcoxon', 'Test de Wilcoxon'), ('mannwhitney', 'Test de Mann-Whitney'), ('kruskal', 'Test de Kruskal-Wallis'), ('spearman', 'Corrélation de Spearman'), ('friedman', 'Test de Friedman'), ('kolmogorov_smirnov', 'Test de Kolmogorov-Smirnov'), ('shapiro_wilk', 'Test de Shapiro-Wilk')], max_length=50)),
                ('test_name', models.CharField(max_length=100)),
                ('selected_columns', models.JSONField()),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('statistic', models.FloatField(blank=True, null=True)),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('alpha', models.FloatField(default=0.05)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('result_data', models.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('is_significant', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de test',
                'verbose_name_plural': 'Historiques de tests',
                'ordering': ['-timestamp'],
            },
        ),
    ]
