# Generated by Django 5.0.6 on 2026-01-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_is_significant'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecasthistory',
            name='model_name',
            field=models.CharField(choices=[('arima', 'ARIMA'), ('sarima', 'SARIMA'), ('prophet', 'Prophet'), ('lstm', 'LSTM'), ('xgboost', 'XGBoost'), ('linear', 'Régression Linéaire'), ('random_forest', 'Random Forest')], default='arima', max_length=50),
        ),
    ]
