# Generated by Django 5.0.6 on 2026-01-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_model_name_to_forecasthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecasthistory',
            name='model_name',
            field=models.CharField(choices=[('arima', 'ARIMA'), ('sarima', 'SARIMA'), ('prophet', 'Prophet'), ('lstm', 'LSTM'), ('xgboost', 'XGBoost'), ('linear', 'Régression Linéaire'), ('random_forest', 'Random Forest')], max_length=50),
        ),
    ]
